# Generated by Django 5.0.7 on 2024-07-23 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_in_dict', models.PositiveIntegerField(blank=True, null=True)),
                ('eng', models.CharField(max_length=100, unique=True)),
                ('ru', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('number_in_dict',),
            },
        ),
        migrations.CreateModel(
            name='IrregularVerb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_form', models.CharField(max_length=30)),
                ('third_form', models.CharField(max_length=30)),
                ('first_form', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='words.word')),
            ],
        ),
    ]
