# Generated by Django 5.0.7 on 2024-08-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_rename_eng_word_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence',
            name='word',
        ),
        migrations.AddField(
            model_name='sentence',
            name='word',
            field=models.ManyToManyField(to='words.word'),
        ),
    ]
