# Generated by Django 5.0.7 on 2024-08-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0006_word_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='en',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='word',
            unique_together={('en', 'ru')},
        ),
    ]
