# Generated by Django 5.0.7 on 2024-08-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0007_alter_word_en_alter_word_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='word',
            field=models.ManyToManyField(to='Word'),
        ),
        migrations.RenameField(
            model_name='sentence',
            old_name='word',
            new_name='words',
        ),
    ]
