# Generated by Django 5.0.7 on 2024-08-21 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0008_remove_sentence_word_sentence_words'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='words',
            field=models.ManyToManyField(related_name='sentences', related_query_name='sentence', to='words.word'),
        ),
        migrations.AlterField(
            model_name='word',
            name='created',
            field=models.DateField(auto_now=True),
        ),
    ]
