# Generated by Django 5.0.7 on 2024-07-30 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('words', '0003_rename_eng_word_en'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('learned', 'Выучено'), ('not_learned', 'Не выучено')], default='not_learned', max_length=12)),
                ('wrong_answer_count', models.PositiveIntegerField(blank=True, default=0)),
                ('correct_answer_count', models.PositiveIntegerField(blank=True, default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.word')),
            ],
        ),
    ]
