# Generated by Django 5.0.7 on 2024-07-30 20:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
        ('words', '0003_rename_eng_word_en'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userword',
            unique_together={('owner', 'word')},
        ),
    ]
