# Generated by Django 5.0.7 on 2024-09-02 17:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vocabulary", "0002_alter_userword_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userword",
            name="created",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="userword",
            name="en",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userword",
            name="ru",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="userword",
            unique_together={("owner", "en", "ru")},
        ),
        migrations.AlterField(
            model_name="userword",
            name="status",
            field=models.CharField(
                choices=[
                    ("learned", "Выучено"),
                    ("learning", "Изучаю"),
                    ("postponed", "Отложено"),
                ],
                default="learning",
                max_length=12,
            ),
        ),
        migrations.RemoveField(
            model_name="userword",
            name="correct_answer_count",
        ),
        migrations.RemoveField(
            model_name="userword",
            name="word",
        ),
        migrations.RemoveField(
            model_name="userword",
            name="wrong_answer_count",
        ),
    ]
