# Generated by Django 5.0.7 on 2024-09-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vocabulary", "0003_alter_userword_unique_together_userword_created_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sentence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("en", models.CharField(max_length=255)),
                ("ru", models.CharField(blank=True, max_length=255)),
                (
                    "words",
                    models.ManyToManyField(
                        related_name="sentences",
                        related_query_name="sentence",
                        to="vocabulary.userword",
                    ),
                ),
            ],
        ),
    ]
